// Generated by MarrowScript compiler. DO NOT EDIT.
// OpenAI-compatible adapter — hits /v1/chat/completions on the configured
// endpoint. Covers vLLM, LM Studio, text-generation-webui, KoboldCPP's OAI
// shim, and OpenAI itself when API key is set.

import type { ChatRequest, ChatResponse, ChatToolCall, IModelProvider } from "./types";
import { approxTokens } from "./types";
import { assertEndpointAllowed } from "./ssrf_guard";

export default class OpenAICompatProvider implements IModelProvider {
  readonly name = "openai_compat";
  private endpoint: string;
  private apiKey: string;

  constructor(endpoint: string, apiKey?: string) {
    assertEndpointAllowed(endpoint);
    this.endpoint = endpoint.replace(/\/+$/, "");
    this.apiKey = apiKey || process.env.OPENAI_COMPAT_API_KEY || "";
  }

  countTokens(text: string): number { return approxTokens(text); }

  async chat(req: ChatRequest, signal?: AbortSignal): Promise<ChatResponse> {
    const body: Record<string, unknown> = {
      model: req.model,
      messages: req.messages,
      temperature: req.temperature ?? 0,
      top_p: req.top_p,
      max_tokens: req.max_output,
      stop: req.stop,
      stream: false,
    };
    if (req.json) body.response_format = { type: "json_object" };
    // Phase 15: forward tools as OpenAI's `tools` array. Each tool maps to
    // OpenAI's function-calling shape: { type: "function", function: { name,
    // description, parameters: <JSON Schema> } }. We never pass `tools` and
    // `response_format: json_object` together — providers that support both
    // tend to ignore one when both are set; the cognition runtime turns off
    // json mode when tools are present and the parser handles raw text.
    if (req.tools && req.tools.length > 0) {
      body.tools = req.tools.map(t => ({
        type: "function",
        function: { name: t.name, description: t.description, parameters: t.parameters },
      }));
      if (req.tool_choice) body.tool_choice = req.tool_choice;
      // Disable response_format when tools are present so providers don't
      // get confused (LM Studio, vLLM both refuse the combination).
      delete body.response_format;
    }
    // Phase 7: ask for top-1 logprobs so we can derive a confidence signal
    // for `router.confidence_threshold`. Many openai-compatible servers
    // (vLLM, LM Studio, text-gen-webui) honour this; those that don't
    // simply ignore it and we fall back to confidence: null.
    body.logprobs = true;
    body.top_logprobs = 1;
    const headers: Record<string, string> = { "Content-Type": "application/json" };
    if (this.apiKey) headers["Authorization"] = `Bearer ${this.apiKey}`;
    const res = await fetch(`${this.endpoint}/chat/completions`, {
      method: "POST",
      headers,
      body: JSON.stringify(body),
      signal,
    });
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      throw new Error(`openai_compat ${res.status}: ${text.slice(0, 256)}`);
    }
    const data = await res.json() as {
      choices?: {
        message?: {
          content?: string;
          tool_calls?: { id?: string; function?: { name?: string; arguments?: string } }[];
        };
        logprobs?: { content?: { logprob?: number }[] };
      }[];
      usage?: { prompt_tokens?: number; completion_tokens?: number };
    };
    const msg = data.choices?.[0]?.message;
    // Phase 15: parse tool_calls if the model invoked any. Defensive: skip
    // entries with missing name or arguments rather than blow up the call.
    const toolCalls: ChatToolCall[] | undefined = Array.isArray(msg?.tool_calls)
      ? msg!.tool_calls!
          .filter(tc => tc && tc.function && typeof tc.function.name === "string")
          .map((tc, i) => ({
            id: tc.id || `tool_${i}`,
            name: tc.function!.name as string,
            arguments: typeof tc.function!.arguments === "string" ? tc.function!.arguments : "{}",
          }))
      : undefined;
    return {
      content: msg?.content || "",
      usage: {
        prompt_tokens: data.usage?.prompt_tokens,
        completion_tokens: data.usage?.completion_tokens,
      },
      confidence: openaiCompatConfidence(data.choices?.[0]?.logprobs?.content),
      tool_calls: toolCalls && toolCalls.length > 0 ? toolCalls : undefined,
      raw: data,
    };
  }
}

/**
 * Map a sequence of per-token logprobs to a single 0..1 confidence value.
 * We use exp(mean(logprob)) — the geometric mean of per-token probabilities.
 * That collapses cleanly to a number every router can compare against
 * `confidence_threshold`. Returns null when no logprobs are present.
 */
function openaiCompatConfidence(content: { logprob?: number }[] | undefined): number | null {
  if (!Array.isArray(content) || content.length === 0) return null;
  let sum = 0;
  let n = 0;
  for (const tok of content) {
    if (typeof tok.logprob === "number" && Number.isFinite(tok.logprob)) {
      sum += tok.logprob;
      n++;
    }
  }
  if (n === 0) return null;
  const mean = sum / n;
  // exp can underflow on very long sequences; clamp to [0, 1].
  const c = Math.exp(mean);
  return Number.isFinite(c) ? Math.max(0, Math.min(1, c)) : null;
}
